### ISSUE TITLE
Tab element persist at the dom.

### ISSUE THREAD

**Issue by zenobiopereira** [EvoluxBR/react-smart-tabs#12]
- Tab element is not removed from the dom after being closed.

**Comment by Mazuh** [comment]
I'll work on this tomorrow!

**Comment by gustavoFreireS** [comment]
@zenobiopereira I'm deleting the tab from the dom (not the ideal approach) on close, so this should not be a problem, but troubleshooting this issue shows me that the tab children on the order hand is not removed from the dom when the actual tab is closed

**Comment by Mazuh** [comment]
@gustavoFreireS but @zenobiopereira is really, the dom elements are still here, this is a resource leak.

![Screenshot from 2019-08-03 17-45-40](https://user-images.githubusercontent.com/6237270/62416740-9c571800-b616-11e9-8772-e64d7a25fdcc.png)

**Comment by Mazuh** [comment]
on this screenshot above, the default form tab is gone, I'm creating new ones and its DOM contents are still existing.

But yes, messing up with DOM and Virtual DOM at the same time is an often cause of bugs like these. Are you using the DOM for any particular reason? maybe an awkward production requirement?
