### ISSUE TITLE
Add the icon and close icon props

### ISSUE THREAD

**Issue by gustavoFreireS** [EvoluxBR/react-smart-tabs#25]
It would be nice if the users could insert a image file or an svg to use it as an icon for the tab and for the close icon (currently it is just the "x" letter), something like it is on the readme image:
![image](https://user-images.githubusercontent.com/8769796/62837510-aa282100-bc46-11e9-8066-fb9cdd56d4d0.png)

**Comment by Mazuh** [comment]
nice idea, and easily passing a whole component as a prop would do the trick
